from MainObjects.League import League
# from Utils import DataScrub
league_object = League.createLeague()

def main():
    # league_object.printSeasonMatchupResults()
    # print()
    # league_object.LeagueStandings() 
    # print()
    # league_object.DivisionStandings(1)
    # print()
    # league_object.DivisionStandings(2)
    # print()
    # league_object.LeagueDraftResults()
    # print()
    league_object.printAllBestTeamStat()
    print()
    # league_object.printTeamRosters()  
    # print()
    # league_object.printTeamByPoints()
    # print()
    # league_object.printTeamByAvgPoints() 
    # print()
    # league_object.printDraftedTeam()
    # print()
    # league_object.printPlayersByAvgPoints()
    # print()
    # league_object.printPlayersByPoints()
    # print()
    # league_object.leagueDraftPowerRankings()
    # print()
    # league_object.leagueCurrPowerRankings()
    # print()
    # league_object.streakReport(team="free_agents", pro_team=["FLA", "LAK", "NJD", "NYI", "OTT", "TOR", "CLS", "NYR", "SJS", "VGK", "WPG", "MTL", "CAR", "ANA", "UTA", "CHI", "VAN"],  min_threshold=1.4)
    # print()
    # league_object.streakReport(team="Dillon's Dubs")    
    # print()
    # league_object.pointPositionReport()
    # print()
    # league_object.getGamesPlayedByTeam()
    # print()
    
    
    
main() 
